Імпортуйте модуль numpy

In [3]:
import numpy as np

# Завдання 1
Створіть масив з елементами від 1 до 12. Виведіть розмір та тип масиву

In [ ]:
x = np.arange(1, 13)
print(x.shape)
type(x)


(12,)


numpy.ndarray

# Завдання 2
Зробіть на основі попереднього масиву матрицю з 4 стовчиками. Змініть тип даних матриці на float32. Виведіть транспоновану матрицю.

In [4]:
x = np.arange(1, 13)
x = np.reshape(x, (3, 4))
x = x.astype("float32")
print(x.T)


[[ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]]


#Завдання 3
Створіть матрицю 8х8 з 0 та 1 розміщеними в шаховому порядку

In [ ]:
x = np.zeros((8, 8), dtype="int64")
x[1::2, ::2] = 1
x[::2, 1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# Завдання 4
Створіть випадкову матрицю 4х3. Знайдіть суму елементів в стовпчиках\рядках\усій матриці

In [ ]:
x = np.random.random((4, 3))
column_sum = np.sum(x, axis=0)
row_sum = np.sum(x, axis=1)
total_sum = np.sum(x)

5.9876907545178835

# Завдання 5
У попередній матриці від кожного рядка відніміть максимальний елемент цього рядка

In [ ]:
max_row = np.max(x, axis=1).reshape(-1, 1)
new_rows = x - max_row
new_rows

array([[-0.06991815,  0.        , -0.45484333],
       [ 0.        , -0.80539806, -0.4732983 ],
       [-0.06416968, -0.76941532,  0.        ],
       [-0.39331583,  0.        , -0.45605273]])

# Завдання 6
Є дані про вагу контейнерів для перевезення на кораблі: дрібний - 5 т,  малий - 10 т, середній - 25 т, великий - 40 т. На кораблі розміщено 20 дрібних, 5 малих, 10 середніх та 4 великих контейнерів. Знайти масу вантажу.

In [ ]:
x = np.array([5, 10, 25, 40])
y = np.array([20, 5, 10, 4])
res = np.sum(x * y)
res

560

# Завдання 7
Тепер у нас декілька кораблів. Напишіть код для обчислення вантажу на кожному кораблі.